"""Turn retained camera-only controller logs into auditable P1 metrics.

This script refuses to invent absent observations: every metric is derived
from the JSONL generated by an actual Webots controller run.
"""

import argparse
import csv
import json
import math
import statistics
from pathlib import Path


def percentile(values, fraction):
    if not values:
        return None
    ordered = sorted(values)
    index = min(len(ordered) - 1, max(0, round((len(ordered) - 1) * fraction)))
    return ordered[index]


def analyse(log):
    rows = [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines() if line.strip()]
    detections = [row for row in rows if row.get("detected") and row.get("estimate_xy") and row.get("evaluation_truth_xy")]
    errors = [
        math.hypot(row["estimate_xy"][0] - row["evaluation_truth_xy"][0], row["estimate_xy"][1] - row["evaluation_truth_xy"][1])
        for row in detections
    ]
    return {
        "robot": log.stem.replace("_camera", ""),
        "samples": len(rows),
        "detections": len(detections),
        "detection_rate": len(detections) / len(rows) if rows else 0.0,
        "position_mae_m": statistics.fmean(errors) if errors else None,
        "position_median_m": statistics.median(errors) if errors else None,
        "position_p90_m": percentile(errors, 0.9),
    }


def svg_report(rows, destination):
    width, height, left, top = 1000, 420, 190, 50
    bar_width = 62
    maximum_error = max([row["position_mae_m"] or 0.0 for row in rows] + [1.0])
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">',
             '<style>text{font-family:Arial,sans-serif;font-size:12px}.title{font-size:18px;font-weight:bold}</style>',
             '<rect width="100%" height="100%" fill="white"/>',
             '<text x="30" y="28" class="title">P1 camera-only evidence: detection rate and world-position MAE</text>',
             '<text x="30" y="48">Blue bar: detection rate (0–100%). Orange bar: MAE normalised to highest measured MAE.</text>']
    for index, row in enumerate(rows):
        x = left + index * 95
        rate_h = 250 * row["detection_rate"]
        error_h = 250 * ((row["position_mae_m"] or 0.0) / maximum_error)
        parts.extend([
            f'<rect x="{x}" y="{top + 250 - rate_h}" width="{bar_width / 2}" height="{rate_h}" fill="#2166ac"/>',
            f'<rect x="{x + bar_width / 2 + 3}" y="{top + 250 - error_h}" width="{bar_width / 2}" height="{error_h}" fill="#e66101"/>',
            f'<text x="{x}" y="{top + 270}" transform="rotate(35 {x} {top + 270})">{row["robot"]}</text>',
            f'<text x="{x}" y="{top + 310}">{row["detection_rate"]:.1%}</text>',
            f'<text x="{x}" y="{top + 326}">{row["position_mae_m"]:.2f}m</text>' if row["position_mae_m"] is not None else f'<text x="{x}" y="{top + 326}">no estimate</text>',
        ])
    parts.extend(['<rect x="30" y="370" width="14" height="14" fill="#2166ac"/><text x="50" y="382">detection rate</text>',
                  '<rect x="155" y="370" width="14" height="14" fill="#e66101"/><text x="175" y="382">position MAE (normalised)</text>',
                  '</svg>'])
    destination.write_text("\n".join(parts), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("evidence_dir", type=Path)
    args = parser.parse_args()
    logs = sorted((args.evidence_dir / "perception").glob("*_camera.jsonl"))
    if not logs:
        raise SystemExit("No controller perception JSONL exists; refusing to create a report.")
    rows = [analyse(log) for log in logs]
    if not any(row["detections"] for row in rows):
        raise SystemExit("No real detections exist; refusing to create a perception score.")

    output = args.evidence_dir / "analysis"
    output.mkdir(exist_ok=True)
    fields = list(rows[0])
    with (output / "perception_metrics.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    summary = {
        "source": str(args.evidence_dir),
        "robots": len(rows),
        "samples": sum(row["samples"] for row in rows),
        "detections": sum(row["detections"] for row in rows),
        "detection_rate": sum(row["detections"] for row in rows) / sum(row["samples"] for row in rows),
        "warning": "Position metrics are a first camera+GPS/IMU projection baseline, not SLAM accuracy.",
    }
    (output / "perception_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    svg_report(rows, output / "perception_metrics.svg")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
